
FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm","start"]



##### To run this : docker run -d -p 3000:3000 -v /app/node_modules -v $(pwd):/app 1869620db4fd
